services:
  database:
    image: "postgres:16.0-alpine3.18"
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres-dev}
    env_file:
      - ../.env.development
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-default}
      POSTGRES_USER: ${POSTGRES_USER:-default}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
