services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  
  # phppgadmin:
  #   restart: always
  #   image: dockage/phppgadmin:latest
  #   ports:
  #   - "80:80"
  #   - "443:443"
  #   environment:
  #   - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
  #   - PHP_PG_ADMIN_SERVER_HOST=localhost
  #   - PHP_PG_ADMIN_SERVER_PORT=5432
  #   - PHP_PG_ADMIN_SERVER_DEFAULT_DB=postgres